---
# tasks file for newrole
- name: install apache
  ansible.builtin.apt:
    name: apache2
    state: present  
- name: start the service
  ansible.builtin.service:
    name: apache2
    state: started
- name: change the port no
  ansible.builtin.template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify:
  - Restart Apache    
- name: change the default page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/    
